spring:
  application:
    name: kudago

  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  servlet:
    encoding:
      force-request: true
      force-response: true
      charset: UTF-8

api:
  base-url: https://kudago.com/public-api/v1.4


jwt-token:
  secret: 77397A24432646294A404E635266556A586E3272357538782F4125442A472D4B
  issuer: polina
cors:
  allowed-origin: http://localhost:3000
admin-data:
  email: admin@admin.ru
  nickname: admin
  password: admin
